### ISSUE TITLE
Problems running FSL on Sherlock

### ISSUE THREAD

**Issue by jpcoetzee76** [poldracklab/lmod_modules#1]
Hello Poldrack Lab, 

I am trying to run FSL on Sherlock and am running into problems. 

I logged in requested sdev, moved to the poldrack software directory, loaded modules "labs" and "poldrack," and then loaded "fsl/6.0.4" and then typed "fsl" to try to bring up the gui. I got this message:

DISPLAY is not set. Please set your DISPLAY environment variable!

Tried to fix this with:
export DISPLAY=localhost:0.0

But now I get these errors:

Application initialization failed: couldn't connect to display "localhost:0.0"
Error in startup script: couldn't connect to display "localhost:0.0"
    while executing
"load /home/groups/russpold/software/fsl-6.0.4/extras/lib/libtk8.4.so Tk"
    ("package ifneeded" script)
    invoked from within
"package require Tk"
    invoked from within
"if { [  string match -nocase *wish* $MYSHELL ] } {
    package require Tk
#    tk_focusFollowsMouse
#bind Button <Enter> { focus %W ; tk::ButtonEnter ..."
    (file "/home/groups/russpold/software/fsl-6.0.4/tcl/fslstart.tcl" line 18)
    invoked from within
"source [ file dirname [ info script ] ]/fslstart.tcl"
    (file "/home/groups/russpold/software/fsl-6.0.4/tcl/fsl.tcl" line 71)
    invoked from within
"source ${FSLDIR}/tcl/${origname}.tcl"
    (file "/home/groups/russpold/software/fsl-6.0.4/bin/fsl" line 22)

Can you advise? Thanks!

PS I'm a postdoc at Stanford in psychiatry

**Comment by oesteban** [comment]
Please check Sherlock's documentation https://www.sherlock.stanford.edu/docs/overview/introduction/ or email the maintainers.

The problem here is that you are probably attempting to bring up FSL's GUI on a headless login- or compute node. For that, I think you'll need to connect to Sherlock with X11Forwarding.

The fact that `$DISPLAY` is not set is just a confirmation that your session is headless (i.e., there's no screen where the Xorg server will be streaming windows).

The problem, therefore is not with the FSL module.
